# Generated by Django 3.1.3 on 2021-03-27 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 11, 28, 24, 310189, tzinfo=utc)),
        ),
    ]
