# Generated by Django 3.1.3 on 2021-03-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210323_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_time',
            field=models.DateTimeField(),
        ),
    ]
