# Generated by Django 3.1.3 on 2021-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210323_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_on',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
