# Generated by Django 3.1.3 on 2021-03-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210327_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_time',
            field=models.DateTimeField(),
        ),
    ]
