# Generated by Django 3.1.3 on 2021-03-27 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210327_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 12, 13, 12, 401632, tzinfo=utc)),
        ),
    ]
