# Generated by Django 3.1.3 on 2021-03-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210327_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwatchlist',
            name='item_id',
        ),
    ]
